# Overrides from https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  DefaultFormatter: fuubar
  DisplayCopNames: true
  ExtraDetails: true
  TargetRubyVersion: 2.4
  TargetRailsVersion: 5.1

# TODO: Re-enable when has_many ... through: ... stops triggering it
Rails/HasManyOrHasOneDependent:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/Send:
  Enabled: true

Style/SingleLineMethods:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/SymbolArray:
  Enabled: true

Style/WhileUntilModifier:
  MaxLineLength: 80

##################### Metrics ##################################

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Exclude:
    - app/admin/**/*.rb

Metrics/BlockNesting:
  Max: 3

Metrics/ClassLength:
  Max: 120

Metrics/ModuleLength:
  Max: 120

Metrics/CyclomaticComplexity:
  Max: 7

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 8

##################### Lint ##################################

# Using all defaults

##################### Performance ############################

# Using all defaults

##################### Rails ##################################

Bundler/OrderedGems:
  Enabled: false

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/Output:
  Include:
    - app/**/*.rb
    - config/**/*.rb
    - db/**/*.rb
    - lib/**/*.rb
    - test/**/*.rb

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false
