profile_thumbnail:
  cron: '0 * * * *'
  class: 'ProfileThumbnailRegenJob'
  queue: default

video_transcoding_status:
  cron: '*/5 * * * *'
  class: 'UpdateTranscodingStatusJob'
  queue: default

fb_og_refresh:
  cron: '0 */6 * * *'
  class: 'FacebookOgRefreshJob'
  queue: default
